### ISSUE TITLE
自训练英文数据

### ISSUE THREAD

**Issue by Tao-Cute** [JeffersonQin/YuzuMarker.FontDetection#25]
想问一下如果自训练一个模型，英文数据大概要怎么构建数据集呢，感谢

**Comment by JeffersonQin** [comment]
你需要准备好字体文件，然后参考我的数据生成脚本：https://github.com/JeffersonQin/YuzuMarker.FontDetection/blob/master/font_ds_generate_script.py

**Comment by Tao-Cute** [comment]
> 你需要准备好字体文件，然后参考我的数据生成脚本：https://github.com/JeffersonQin/YuzuMarker.FontDetection/blob/master/font_ds_generate_script.py
指的是一些.ttf文件吗~我对这部分不太熟悉~

**Comment by JeffersonQin** [comment]
嗯，那你可能得多研究研究，这东西大半年前写的了，代码结构比较乱

**Comment by Tao-Cute** [comment]
> 嗯，那你可能得多研究研究，这东西大半年前写的了，代码结构比较乱

感谢~
