### ISSUE TITLE
请问大佬，font_demo_cache.bin开源了吗

### ISSUE THREAD

**Issue by Yasuharaaa** [JeffersonQin/YuzuMarker.FontDetection#26]
请问有输出label具体的字体名列表吗

**Comment by JeffersonQin** [comment]
开源了。

https://github.com/JeffersonQin/YuzuMarker.FontDetection/blob/be479297967247530a49fb1285297e5a6969ecfe/demo.py#L141-L156

文件在这个 docker 内自己 exec /bin/bash 进去看，我本地也没这个文件了：https://hub.docker.com/repository/docker/jeffersonqin/yuzumarker.fontdetection.huggingfacespace.base/general

**Comment by LizzyEw** [comment]
> 开源了。
> 
> [YuzuMarker.FontDetection/demo.py](https://github.com/JeffersonQin/YuzuMarker.FontDetection/blob/be479297967247530a49fb1285297e5a6969ecfe/demo.py#L141-L156)
> 
> Lines 141 to 156 in [be47929](/JeffersonQin/YuzuMarker.FontDetection/commit/be479297967247530a49fb1285297e5a6969ecfe)
> 
>  def prepare_fonts(cache_path="font_demo_cache.bin"): 
>      print("Preparing fonts ...") 
>      if os.path.exists(cache_path): 
>          return pickle.load(open(cache_path, "rb")) 
>   
>      font_list, exclusion_rule = load_fonts() 
>   
>      font_list = list(filter(lambda x: not exclusion_rule(x), font_list)) 
>      font_list.sort(key=lambda x: x.path) 
>   
>      for i in range(len(font_list)): 
>          font_list[i].path = font_list[i].path[18:]  # remove ./dataset/fonts/./ prefix 
>   
>      with open(cache_path, "wb") as f: 
>          pickle.dump(font_list, f) 
>      return font_list 
> 文件在这个 docker 内自己 exec /bin/bash 进去看，我本地也没这个文件了：https://hub.docker.com/repository/docker/jeffersonqin/yuzumarker.fontdetection.huggingfacespace.base/general

docker hub 显示没有权限访问页面 Not Authorized You are not authorized to view this page.  请问有别的方式查看当年的 font_demo_cache.bin 嘛，十分感谢！

**Comment by JeffersonQin** [comment]
不是在 dockerhub 上看，你把这个image pull下来然后启动，用 `docker exec /bin/bash` 看

我最近手边没有能用的电脑，你看看行不行

**Comment by LizzyEw** [comment]
> 不是在 dockerhub 上看，你把这个image pull下来然后启动，用 `docker exec /bin/bash` 看
> 
> 我最近手边没有能用的电脑，你看看行不行

感谢回复！我手边电脑不能装 docker 也没办法拉镜像，还是谢谢大佬
